-- Supabase schema for ToDoApp (Path B: frontend talks to Supabase directly).
-- Run once in the Supabase SQL Editor.
--
-- Security model: single-user app. Signups are disabled in Auth settings,
-- so "any authenticated user" means "you". Tables are NOT exposed to anon.

-- ── Tables ──────────────────────────────────────────────────────────────────

create table todos (
  id          bigint generated by default as identity primary key,
  title       text not null check (char_length(title) between 1 and 255),
  description text,
  priority    text not null default 'medium' check (priority in ('low', 'medium', 'high')),
  status      text not null default 'pending' check (status in ('pending', 'done')),
  due_date    date,
  due_time    time,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create table wishlist_categories (
  id         bigint generated by default as identity primary key,
  name       text not null check (char_length(name) between 1 and 255),
  created_at timestamptz not null default now()
);

create table wishlist_items (
  id          bigint generated by default as identity primary key,
  category_id bigint not null references wishlist_categories (id) on delete cascade,
  name        text not null check (char_length(name) between 1 and 255),
  description text,
  url         text,
  price       numeric(10, 2) check (price >= 0),
  purchased   boolean not null default false,
  created_at  timestamptz not null default now()
);

-- ── updated_at maintenance ──────────────────────────────────────────────────

create extension if not exists moddatetime schema extensions;

create trigger todos_updated_at
  before update on todos
  for each row execute procedure extensions.moddatetime (updated_at);

-- ── Row Level Security ───────────────────────────────────────────────────────
-- Enabled explicitly (belt and braces alongside the project's automatic-RLS
-- trigger). No anon policies: logged-out visitors see nothing.

alter table todos enable row level security;
alter table wishlist_categories enable row level security;
alter table wishlist_items enable row level security;

create policy "authenticated full access" on todos
  for all to authenticated using (true) with check (true);

create policy "authenticated full access" on wishlist_categories
  for all to authenticated using (true) with check (true);

create policy "authenticated full access" on wishlist_items
  for all to authenticated using (true) with check (true);

-- ── API exposure ─────────────────────────────────────────────────────────────
-- "Automatically expose new tables" is off for this project, so grant access
-- deliberately — and only to the authenticated role.

grant select, insert, update, delete on todos, wishlist_categories, wishlist_items to authenticated;
grant usage, select on all sequences in schema public to authenticated;
